apiVersion: v1
kind: Service
metadata:
  name: vllm
  namespace: week6-llm
  labels:
    app.kubernetes.io/name: vllm
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8000"
spec:
  selector:
    app.kubernetes.io/name: vllm
  ports:
    - name: metrics-http
      port: 8000
      targetPort: http
